### ISSUE TITLE
[Feature Request] Create config field to only track specific NPC IDs

### ISSUE THREAD

**Issue by iProdigy** [branisk/runelite-afkspot-finder#2]
For scenarios where multiple types of NPCs are loaded, but the user only cares about AFKing a certain npc id, it would be nice if the tile density only reflected the movement of the specific npc id (or comma-separated list of id's).

**Comment by branisk** [comment]
Done.  Commit 0786915a520690c1a6f5b2a088cce58c4446da3b solves this. only one NPC can be added for now, if left blank then any npc works.  Can easily be implemented if there are many situations where you want to allow more than one npc but less than all of the surrounding NPCs.
