### ISSUE TITLE
Fix the tiles not resetting after removing an NPC in config

### ISSUE THREAD

**Issue by branisk** [branisk/runelite-afkspot-finder#7]
### Expected Behavior
Tiles should be reset when NPC changes are made in the config, more specifically when an NPC is removed, it's calculated tiles should also be removed.

### Current Behavior
When adding an NPC, or removing an NPC, the tiles for the NPC's that existed before any changes are still taken into account for displaying the most dense tiles. I think it would make sense to reset the tiles or remove the tiles of any NPC's that are removed.

### Steps to Reproduce
1. Add a new NPC after a comma in config, remove the old NPC, then click inside of the game and see that the removed NPC's tiles still displayed

**Comment by iProdigy** [comment]
I can't reproduce this on https://github.com/branisk/runelite-afkspot-finder/commit/a60dcde5cdf6894bbd9843c4900bcecd12d868be (but it was an issue in the previous commit)

**Comment by branisk** [comment]
Okay thanks I'll double check tomorrow and close this accordingly

**Comment by branisk** [comment]
Double checked, issue resolved by a60dcde5cdf6894bbd9843c4900bcecd12d868be.
